config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence:true, length: 2..200
	validates :description, presence:true, length: 10..1000
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :get_article, only: [:edit, :update, :show, :destroy]

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		# render plain: params[:article].inspect
		@article = Article.new(article_params_check)

		if @article.save
			flash[:success] = "Post was successfully posted."
			redirect_to article_path(@article)
		else
			render :new
		end
	end

	def edit
		# @article = Article.find(params[:id])
	end

	def update
		# @article = Article.find(params[:id])

		if @article.update(article_params_check)
			flash[:success] = "Post was successfully updated."
			redirect_to article_path(@article)
		else
			render :edit
		end
	end

	def show
		# @article = Article.find(params[:id])
	end

	def destroy
		# @article = Article.find(params[:id])
		@article.destroy

		flash[:danger] = "Post was successfully deleted."
		redirect_to articles_path
	end

	private
	def get_article
		@article = Article.find(params[:id])
	end

	def article_params_check
		params.require(:article).permit(:title, :description)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end

	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |post| %>
			<div class="form-group">
				<div class="col-sm-12">
					<%= post.text_field :title, placeholder: "Title", class:"form-control", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-12">
					<%= post.text_area :description,rows: 10, placeholder: "description", class:"form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-8 col-sm-offset-2" align="center">
					<%= post.submit "Save", class: "btn btn-primary btn-lg" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/articles/create.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	
</body>
</html>

app/views/articles/edit.html.erb
<h1 align="center">Edit your post <%= link_to 'or not', article_path %></h1>
<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center" class="all-article-heading">
    All Articles
</h1>

<% if @articles.length < 0 %>
<h3>
    <%= link_to "Write your first post!", new_article_path %>
</h3>
<% end %>
<% else %>
<% @articles.reverse_each do |article| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%= link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
					<%= truncate(article.description, length: 100) %>
				</div>
				<div class="article-timestamp">
					<%= article.updated_at %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/new.html.erb
<h1 align="center">Something new today? or <%= link_to 'see all posts', articles_path %></h1>
<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
	<div class="description">
		<h3>
			<small><%= simple_format(@article.description) %></small>
		</h3>
	</div>

	<div class="article-actions">
		<%= link_to 'Edit Post', edit_article_path, class: "btn btn-xs btn-primary" %>
		<%= link_to 'Delete Post', article_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
		<%= link_to 'All Posts', articles_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="container">
        <h3>
            <small>
                <p>
                    Alpha Blog 2016 devloped by
                    <a href="http://github.com/cyberrob">
                        R.W.
                    </a>
                </p>
            </small>
        </h3>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class="close" data-dimiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All Posts", articles_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create Post", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>
		AlphaBlog
		</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>
		true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' =>
		true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/navigation'  %>
		<%= render 'layouts/messages' %>
		<div id="container">
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>

app/views/pages/about.html.erb
<DOCTYPE <!DOCTYPE html>
    <html>
        <head>
            <title>
                About
            </title>
        </head>
        <body>
            <h1>
                This is About Page
            </h1>
            <table>
                <tr>
                    <td colspan="2">
                        <%= link_to image_tag('girl.jpg', :style=>
                            "width:75%;height:75%"),  'https://www.facebook.com/kyoza30?fref=ts'  %>
                        <p>Courtesy of <a href="https://www.facebook.com/kyoza30">陳紀東</a></p>
                        </td>
                    </tr>
                    <tr>
                    	<td>
                    		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat molestias totam incidunt harum eius cum dicta quisquam ad cumque, quia provident a sit! Repudiandae accusantium delectus libero velit amet at!</p>
                    		<p>Mollitia modi eum, esse numquam illum impedit ducimus, ad voluptas ullam dolorem, quia dolores, similique. Reprehenderit iure harum sit odio repellendus. Quam iste labore, quod sunt eos inventore repudiandae similique?</p>
                    	</td>
                    	<td>
                    		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit rerum illo aliquam exercitationem aut ratione nisi? Non, quisquam aperiam ea totam magni laboriosam, libero nulla veniam similique et, fugiat adipisci.</p>
                    		<p>Quisquam facilis vero perspiciatis sint voluptatum aperiam eveniet soluta? Nobis tenetur, at autem, delectus dolore vitae impedit distinctio, mollitia dolores accusamus quae praesentium. Sed sequi nam, ab mollitia odio, numquam!</p>
                    	</td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <%= link_to 'home', root_path %>
                            </td>
                        </tr>
                    </table>
                    <h4 style="text-align: center;font-family: courier">All rights reserved 2016</h4>
                </body>
            </html>

app/views/pages/contact.html.erb
<h1>
Contact Us
</h1>
<table>
    <tr>
        <td colspan="2">
            <%= link_to image_tag('girl.jpg', :style=>
            "width:75%;height:75%"),  'https://www.facebook.com/kyoza30?fref=ts'  %>
            <p>Courtesy of <a href="https://www.facebook.com/kyoza30">陳紀東</a></p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat molestias totam incidunt harum eius cum dicta quisquam ad cumque, quia provident a sit! Repudiandae accusantium delectus libero velit amet at!</p>
            <p>Mollitia modi eum, esse numquam illum impedit ducimus, ad voluptas ullam dolorem, quia dolores, similique. Reprehenderit iure harum sit odio repellendus. Quam iste labore, quod sunt eos inventore repudiandae similique?</p>
        </td>
        <td>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit rerum illo aliquam exercitationem aut ratione nisi? Non, quisquam aperiam ea totam magni laboriosam, libero nulla veniam similique et, fugiat adipisci.</p>
            <p>Quisquam facilis vero perspiciatis sint voluptatum aperiam eveniet soluta? Nobis tenetur, at autem, delectus dolore vitae impedit distinctio, mollitia dolores accusamus quae praesentium. Sed sequi nam, ab mollitia odio, numquam!</p>
        </td>
    </tr>
    
</table>
<h4 style="text-align: center;font-family: courier">All rights reserved 2016</h4>

app/views/pages/home.html.erb
<div align="center" class="container">
    <div class="jumbotron">
        <blockquote class="blockquote-reverse">
            <p align="right">
                The shadows under the trees <br>
                And in the vines by the boat-house<br>
                Grow dark,<br>
                And the lamps gleam softly.<br><br>

                On the street, far off,<br>
                The sound of the cars, rumbling,<br>
                Moves drowsily.<br>
                The rocks grow dim on the edges of the shore.<br><br>

                The boats with tired prows against the landing<br>
                Have fallen asleep heavily:<br>
                The monuments sleep<br>
                And the trees<br>
                And the smooth slow-winding empty paths sleep.<br>
            </p>
            <footer>Helen Hoyt - Park Going to Sleep</footer>
        </blockquote>

            <%= link_to "TRY IT", new_article_path, class: "btn btn-default btn-lg", role: "button" %>
        <br><br>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this article from being saved.
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>